--!strict

local FrameComponents = {
	Lobby = require(script.Lobby),
	GamePlay = require(script.GamePlay),
	MapSelection = require(script.MapSelection),
	Notifications = require(script.Notifications),
	Opened = require(script.Opened),
	Settings = require(script.Settings),
	Inventory = require(script.Inventory),
	ShopHolder = require(script.Shop),
	Spinning = require(script.Spinning),
	Stats = require(script.Stats),
	-- Leaderboard = require(script.Leaderboard),
}

return FrameComponents
